dist: xenial
language: python
sudo: false
cache: pip
python:
- '3.6'
- '3.5'
- '2.7'
env:
- PACKAGES="django>=1.11,<1.12"
- PACKAGES="django>=2.0,<2.1"
matrix:
  exclude:
  - python: '2.7'
    env: PACKAGES="django>=2.0,<2.1"
  include:
  - python: '3.6'
    env: PACKAGES="django>=2.1,<2.2"
  - python: '3.6'
    env: PACKAGES="django>=2.2,<2.3"
  - python: '3.6'
    env: PACKAGES="django>=3.0,<3.1"
before_install:
- pip install codecov
install:
- pip install -U pip wheel setuptools
- pip install $PACKAGES -e .[tests]
script:
- coverage run --rcfile=.coveragerc runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.freenode.org#django-fluent
    template:
    - '%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}'
    skip_join: true
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: CJ+oORfxdm/EQDbIbQ8VZmPLgA15wohO7tv5RpgZXnuTBIWrWE/DwGULqms8P6qiDgHyvR/S8g2wGdaS2HXdz/aDpPPfypyRJJu9y1mupuv1tG2NkN7+7qmjRhjTrn9vvo5I8GaEGKtGVh5jMeahsZkqrYykmLB9rsHoyhZwNmo=
    on_success: never
    on_failure: always
